### ISSUE TITLE
voice-agent deploy error

### ISSUE THREAD

**Issue by Gitcqs** [CerebriumAI/examples#35]
run cerebrium deploy
then result
TypeError: __init__() got an unexpected keyword argument 'docker_base_image_url'

**Comment by aos-musculo** [comment]
Comment out the line docker_base_image_url in your cerebrium.yaml. The example doc mentions this feature is coming but its not super clear.

**Comment by milo157** [comment]
You need the docker_base_image_url in your cerebrium.toml in order to have the local Deepgram images on your instance. If you join our Slack or Discord community it would be best to message me there with your projectId so I can investigate

**Comment by milo157** [comment]
@Gitcqs Please check you have the latest cerebrium CLI version. It should be >=1.23.0.  if not you might need to update your pip and run pip install --upgrade cerebrium
